### ISSUE TITLE
SUSE LINUX 10 无法运行该工具

### ISSUE THREAD

**Issue by wuyuanyong** [dblucyne/dodba_tools#2]
1、配置文件
oracle@cbdb:~/bin/dodba_tools-master> cat doDBA.conf 
{
"Host":"",
"Huser": "root",
"Hport": "22",
"Hpwd":  "wyong%123",
"Muser": "dodba",
"Mpwd":  "dodba",
"Mport":"3306"
}

2、运行工具
oracle@cbdb:~/bin/dodba_tools-master> ./doDBA -h=10.0.1.27 -sys
2016/12/19 13:40:58 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
--出现如上错误

3、系统环境
3.1、OS内核:
oracle@cbdb:~/bin/dodba_tools-master> uname -r
2.6.16.60-0.85.1-smp

3.2、OS版本
oracle@cbdb:~/bin/dodba_tools-master> cat /etc/issue
Welcome to SUSE Linux Enterprise Server 10 SP4  (x86_64) - Kernel \r (\l).

**Comment by dblucyne** [comment]
信任有问题，关注wechat：dodba沟通吧。

**Comment by wuyuanyong** [comment]
已加微信，我是在本机运行的 也就是说我是在10.0.1.27 这台服务器上运行dodba出现这个问题 #
