### ISSUE TITLE
命令行中-mP=xxx 不支持非3306的MySQL端口？

### ISSUE THREAD

**Issue by taohuixiang** [dblucyne/dodba_tools#3]
命令行中-mP=xxx  不生效？ 测试时发现仍是使用3306端口。

**Comment by dblucyne** [comment]
目前只有-h 可以覆盖doDBA.conf中的参数，可以修改doDBA.conf中的Mport，也可以删除doDBA.conf中的Mport一行，使用-mP=xxx

**Comment by dblucyne** [comment]
目前参数优先级已经高于命令行高于配置文件，对DBA使用更友好，欢迎下载最新版。
