### ISSUE TITLE
长时间运行监控会有内存泄露的情况发生

### ISSUE THREAD

**Issue by phoenix8459** [dblucyne/dodba_tools#9]
top - 22:58:32 up 42 days, 13:03,  1 user,  load average: 7.62, 8.64, 8.37
Tasks: 156 total,   1 running, 155 sleeping,   0 stopped,   0 zombie
Cpu(s):  1.7%us,  1.7%sy,  0.0%ni, 43.1%id, 53.3%wa,  0.0%hi,  0.1%si,  0.1%st
Mem:   8061452k total,  7948132k used,   113320k free,    12588k buffers
Swap:  8388604k total,  4194424k used,  4194180k free,    37664k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                
 2874 mysql     20   0 9293m 707m 3568 S  4.7  9.0   1265:54 mysqld                                                                                                 
31658 root      20   0 9039m 6.4g 1376 S  1.0 83.8   1592:30 doDBA

**Comment by dblucyne** [comment]
麻烦提供一下执行的具体命令，多谢

**Comment by phoenix8459** [comment]
./doDBA -h=192.168.XX.XX -myall -t=600 -log

另外，执行过程中被监控机 SSH被关闭了，不能够在监控主机状态，可能是这个有一定原因吧
